In [ ]:
pip install numpy


In [17]:
import numpy as np

# Create a numpy array containing numbers from 1 to 10
array1 = np.arange(1, 11)
print (array1)

# Reshape the array to a 2x5 matrix
Array_2D = array1.reshape(2, 5)

print(matrix)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
# Create a NumPy array with numbers from 1 to 20
Array2 = np.arange(1, 21)

# Extract elements between the 5th and 15th index (both inclusive)
Array2_extracted = Array2[5:16]

print(Array2_extracted)

[ 6  7  8  9 10 11 12 13 14 15 16]


In [56]:
import pandas as pd

# Create the initial Pandas Series
data = {'oranges': 1,'bananas': 2,'apples': 3 }
series = pd.Series(data)
# display the initial Pandas Series
print(data)
# Add a new item to the series
series['pears'] = 4

# Display the updated series
print(series)


{'oranges': 1, 'bananas': 2, 'apples': 3}
oranges    1
bananas    2
apples     3
pears      4
dtype: int64


In [60]:
# Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
Account_details = {
    'name': ['Manu', 'Anu', 'Thanu', 'Rejith', 'Divya', 'Jonah', 'Maria', 'Tessa', 'Raju', 'Jincy'],
    'age': [40, 15, 38, 45, 42, 15, 16, 10, 50, 40],
    'gender': ['M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}

# Creating the dataframe
df = pd.DataFrame(Account_details)

print(df)

     name  age gender
0    Manu   40      M
1     Anu   15      F
2   Thanu   38      F
3  Rejith   45      M
4   Divya   42      F
5   Jonah   15      M
6   Maria   16      F
7   Tessa   10      F
8    Raju   50      M
9   Jincy   40      F


In [62]:
#Add a new column to the data frame created  earlier, called "occupation". 
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. 
occupation=['programmer','Manager','Analyst','Manager','programmer','Analyst','Manager','programmer','Manager','Analyst']
df['Occupation']=occupation
print(df)


     name  age gender  Occupation
0    Manu   40      M  programmer
1     Anu   15      F     Manager
2   Thanu   38      F     Analyst
3  Rejith   45      M     Manager
4   Divya   42      F  programmer
5   Jonah   15      M     Analyst
6   Maria   16      F     Manager
7   Tessa   10      F  programmer
8    Raju   50      M     Manager
9   Jincy   40      F     Analyst


In [64]:
# Select rows where age is greater than or equal to 30
Age_Selected_df = df[df['age'] >= 30]

print(Age_Selected_df)

     name  age gender  Occupation
0    Manu   40      M  programmer
2   Thanu   38      F     Analyst
3  Rejith   45      M     Manager
4   Divya   42      F  programmer
8    Raju   50      M     Manager
9   Jincy   40      F     Analyst


In [72]:
# Converting the dataframe to a CSV file
Age_Selected_df.to_csv('dataframe.csv', index=False)

# Reading the CSV file
df_from_csv = pd.read_csv('dataframe.csv')
# Display the contents of the CSV file
print(df_from_csv)


     name  age gender  Occupation
0    Manu   40      M  programmer
1   Thanu   38      F     Analyst
2  Rejith   45      M     Manager
3   Divya   42      F  programmer
4    Raju   50      M     Manager
5   Jincy   40      F     Analyst


In [74]:
import os

In [76]:
print(os.getcwd())

C:\Users\asus


In [82]:
df_from_csv

name  age gender  Occupation
0    Manu   40      M  programmer
1   Thanu   38      F     Analyst
2  Rejith   45      M     Manager
3   Divya   42      F  programmer
4    Raju   50      M     Manager
5   Jincy   40      F     Analyst